# --------------------------------------------------------------------------------------------------------------------------



# EarthBound Battle Background Previewer

# https://github.com/Vittorioux/EBBG-Previewer

# Constants file.



# -------------------------------------------------------- Imports ---------------------------------------------------------



import os



# ------------------------------------------------------- Constants --------------------------------------------------------



# Folder and file where some of the application data will be stored.

DATA_FOLDER_NAME = "ebbg-previewer_data"
DATA_FILE_NAME = os.path.join(DATA_FOLDER_NAME, "data.conf")

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# SuperFamiconV will produce some temporary files.

# BG1.
TEMP_PALETTE_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_palette_out_1.bin")
TEMP_TILES_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_tiles_out_1.bin")
TEMP_TILEMAP_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_tilemap_out_1.bin")

#BG2.
TEMP_PALETTE_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_palette_out_2.bin")
TEMP_TILES_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_tiles_out_2.bin")
TEMP_TILEMAP_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_tilemap_out_2.bin")

# Temp images with corrected formats.
TEMP_IMG_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_img_out_1.png")
TEMP_IMG_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_img_out_2.png")

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Program version.

VERSION = "1.02"

# 'About' text.

ABOUT_TEXT = f"""EarthBound BG Previewer v{VERSION}

Use this simple program to quickly preview palette cycling, scrolling and distortion settings on EarthBound battle backgrounds.

This program and its source code operate under an MIT License:
https://github.com/Vittorioux/EBBG-Previewer

This program uses Inhal by devinacker and SuperFamiconV by Optiroc.

Inhal/Exhal:
https://github.com/devinacker/exhal

SuperFamiconV:
https://github.com/Optiroc/SuperFamiconv"""

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Field names in the top frame.

t_field_names = ["setting_emulator", "setting_rom", "setting_bg1", "setting_bg2"]

m_field_names_palette = ["setting_bpp", "setting_cyc_type", "setting_cyc_1_begin", "setting_cyc_1_end", "setting_cyc_2_begin", "setting_cyc_2_end", "setting_cyc_speed"]

m_field_names_scroll = ["setting_scr_check", "setting_scr_dur", "setting_scr_hacc", "setting_scr_hmov", "setting_scr_vacc", "setting_scr_vmov"]

m_field_names_distortion = ["setting_dst_check", "setting_dst_type", "setting_dst_rip_amp", "setting_dst_rip_amp_acc", "setting_dst_rip_freq", "setting_dst_rip_freq_acc", "setting_dst_acc", "setting_dst_spd", "setting_dst_cr", "setting_dst_cr_acc", "setting_dst_dur"]

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Default data file contents (the first four names are hardcoded).

DEFAULT_DATA = f"""# DO NOT EDIT THIS FILE

width: 800
height: 575
x_pos: 100
y_pos: 100

{t_field_names[0]}: 
{t_field_names[1]}: 
{t_field_names[2]}: 
{t_field_names[3]}: 
"""

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Other constants.

BANK_C0_OFFSET = 0xC00000

CYCLE_TYPE_NAMES = ["None", "Cycle 1", "Cycle 1+2", "Cycle 1 (reverse)"]
DST_TYPE_NAMES = ["None (Unk type 0)", "Horizontal, smooth", "Horizontal, interlaced", "Vertical, smooth", "Hor, interl 2 (Unk type 4)"]

GFX_25_OFFSET = 0xCB73CB
ARR_25_OFFSET = 0xCBC200
PAL_25_OFFSET = 0xCBD3B4

GFX_50_OFFSET = 0xCBD6D2
ARR_50_OFFSET = 0xCB9A71
PAL_50_OFFSET = 0xCBD094

SCR_ENTRY_SIZE = 10
DST_ENTRY_SIZE = 17

MENU_BG1_OFFSET = 0xC0B5F1
MENU_BG2_OFFSET = 0xC0B5EC

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Tuple of dicts with forced ROM insertions.

forced_rom_insertions = (
	
	# ASM Code to make it so the game goes directly to show the BGs.
	
	{"offset": 0xC0B7EB, "bytes": [0x80, 0x02]},                           # Skip intro logos, gas station screen, title.
	
	# Constantly animate the background, plus detect Y button for pause and L button to switch letterbox size.
	{"offset": 0xC1ED6A, "bytes": [0x64, 0x0E, 0xA2, 0x00, 0x02, 0xA9, 0x00, 0x02, 0x22, 0xFC, 0x8E, 0xC0, 0xA9, 0x02, 0x00, 0x22, 0xE8, 0x29, 0xC4, 0x22, 0x3F, 0xDB, 0xC2, 0x22, 0x71, 0xAB, 0xC2, 0x22, 0x56, 0x87, 0xC0, 0xAD, 0x65, 0x00, 0x29, 0x00, 0x40, 0xD0, 0xF4, 0x80, 0xEA, 0x1E, 0x98, 0xE2, 0x20, 0x18, 0x69, 0x61, 0x8D, 0x9F, 0x9C, 0xA9, 0x6A, 0x8D, 0xA0, 0x9C, 0xA9, 0x50, 0x8D, 0xA1, 0x9C, 0xA2, 0x00, 0x00, 0x80, 0x1B, 0xE2, 0x20]},
	
	# Implement letterbox switching routine in the ROM where the unused Teleport Box battle action.
	{"offset": 0xC2AB71, "bytes": [0xAD, 0x6D, 0x00, 0x29, 0x20, 0x00, 0xF0, 0x38, 0xAD, 0xB2, 0xAD, 0xF0, 0x18, 0xC9, 0x42, 0x00, 0xF0, 0x21, 0x18, 0x69, 0x0A, 0x00, 0x8D, 0xB2, 0xAD, 0xAD, 0xB4, 0xAD, 0x38, 0xE9, 0x0A, 0x00, 0x8D, 0xB4, 0xAD, 0x80, 0x17, 0xA9, 0x2E, 0x00, 0x8D, 0xB2, 0xAD, 0xA9, 0xB1, 0x00, 0x8D, 0xB4, 0xAD, 0x80, 0x09, 0x9C, 0xB2, 0xAD, 0xA9, 0xE0, 0x00, 0x8D, 0xB4, 0xAD, 0x22, 0xAC, 0xD0, 0xC2, 0x6B]},
	
	{"offset": MENU_BG1_OFFSET, "bytes": [0x01]},                          # Load background 1 as layer 1.
	{"offset": MENU_BG2_OFFSET, "bytes": [0x02]},                          # Load background 2 as layer 2.
	
	{"offset": 0xC2FFFF, "bytes": [0xEA]},                                 # "ROM was modified by this program" mark.
	
	# BG1.
	
	{"offset": 0xCADCB2, "bytes": [0x19]},                                 # Graphics.
	{"offset": 0xCADCB3, "bytes": [0x19]},                                 # Palette.
	
	{"offset": 0xCADCBB, "bytes": [0x01]},                                 # SCR1.
	{"offset": 0xCADCBC, "bytes": [0x02]},                                 # SCR2.
	{"offset": 0xCADCBD, "bytes": [0x03]},                                 # SCR3.
	{"offset": 0xCADCBE, "bytes": [0x04]},                                 # SCR4.
	
	{"offset": 0xCADCBF, "bytes": [0x01]},                                 # DST1.
	{"offset": 0xCADCC0, "bytes": [0x02]},                                 # DST2.
	{"offset": 0xCADCC1, "bytes": [0x03]},                                 # DST3.
	{"offset": 0xCADCC2, "bytes": [0x04]},                                 # DST4.
	
	# BG2.
	
	{"offset": 0xCADCC3, "bytes": [0x32]},                                 # Graphics.
	{"offset": 0xCADCC4, "bytes": [0x32]},                                 # Palette.
	
	{"offset": 0xCADCCC, "bytes": [0x05]},                                 # SCR1.
	{"offset": 0xCADCCD, "bytes": [0x06]},                                 # SCR2.
	{"offset": 0xCADCCE, "bytes": [0x07]},                                 # SCR3.
	{"offset": 0xCADCCF, "bytes": [0x08]},                                 # SCR4.
	
	{"offset": 0xCADCD0, "bytes": [0x05]},                                 # DST1.
	{"offset": 0xCADCD1, "bytes": [0x06]},                                 # DST2.
	{"offset": 0xCADCD2, "bytes": [0x07]},                                 # DST3.
	{"offset": 0xCADCD3, "bytes": [0x08]}                                  # DST4.
)

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Tuples of dicts for ROM insertions, containing each relevant field, its ROM offset, field type, and data type.

# Valid field types are 'combobox_val', 'combobox_idx', 'check' and 'entry'.

# Valid data types are 'byte' and 'short'.

# (Full customization isn't properly programmed in 'logic.py' as of now).

insertions_palette = (
	
	# BG1, palette settings.

	{"name": m_field_names_palette[0] + "_bg1", "offset": 0xCADCB4, "type": "byte", "field": "combobox_val"},                # BPP.
	{"name": m_field_names_palette[1] + "_bg1", "offset": 0xCADCB5, "type": "byte", "field": "combobox_idx"},                # Type.
	{"name": m_field_names_palette[2] + "_bg1", "offset": 0xCADCB6, "type": "byte", "field": "entry"},                       # Cycle 1 begin.
	{"name": m_field_names_palette[3] + "_bg1", "offset": 0xCADCB7, "type": "byte", "field": "entry"},                       # Cycle 1 end.
	{"name": m_field_names_palette[4] + "_bg1", "offset": 0xCADCB8, "type": "byte", "field": "entry"},                       # Cycle 2 begin.
	{"name": m_field_names_palette[5] + "_bg1", "offset": 0xCADCB9, "type": "byte", "field": "entry"},                       # Cycle 2 end.
	{"name": m_field_names_palette[6] + "_bg1", "offset": 0xCADCBA, "type": "byte", "field": "entry"},                       # Speed.
	
	# BG2, palette settings.
	
	{"name": m_field_names_palette[0] + "_bg2", "offset": 0xCADCC5, "type": "byte", "field": "combobox_val"},                # BPP.
	{"name": m_field_names_palette[1] + "_bg2", "offset": 0xCADCC6, "type": "byte", "field": "combobox_idx"},                # Type.
	{"name": m_field_names_palette[2] + "_bg2", "offset": 0xCADCC7, "type": "byte", "field": "entry"},                       # Cycle 1 begin.
	{"name": m_field_names_palette[3] + "_bg2", "offset": 0xCADCC8, "type": "byte", "field": "entry"},                       # Cycle 1 end.
	{"name": m_field_names_palette[4] + "_bg2", "offset": 0xCADCC9, "type": "byte", "field": "entry"},                       # Cycle 2 begin.
	{"name": m_field_names_palette[5] + "_bg2", "offset": 0xCADCCA, "type": "byte", "field": "entry"},                       # Cycle 2 end.
	{"name": m_field_names_palette[6] + "_bg2", "offset": 0xCADCCB, "type": "byte", "field": "entry"}                        # Speed.
)

insertions_check = (
	
	# BG1, scroll checks.
	
	{"name": m_field_names_scroll[0] + "_bg1_scr1", "offset": 0xCADCBB, "type": "byte", "field": "check"},                   # SCR1.
	{"name": m_field_names_scroll[0] + "_bg1_scr2", "offset": 0xCADCBC, "type": "byte", "field": "check"},                   # SCR2.
	{"name": m_field_names_scroll[0] + "_bg1_scr3", "offset": 0xCADCBD, "type": "byte", "field": "check"},                   # SCR3.
	{"name": m_field_names_scroll[0] + "_bg1_scr4", "offset": 0xCADCBE, "type": "byte", "field": "check"},                   # SCR4.
	
	# BG1, distortion checks.
	
	{"name": m_field_names_distortion[0] + "_bg1_dst1", "offset": 0xCADCBF, "type": "byte", "field": "check"},               # DST1.
	{"name": m_field_names_distortion[0] + "_bg1_dst2", "offset": 0xCADCC0, "type": "byte", "field": "check"},               # DST2.
	{"name": m_field_names_distortion[0] + "_bg1_dst3", "offset": 0xCADCC1, "type": "byte", "field": "check"},               # DST3.
	{"name": m_field_names_distortion[0] + "_bg1_dst4", "offset": 0xCADCC2, "type": "byte", "field": "check"},               # DST4.
	
	# BG2, scroll checks.
	
	{"name": m_field_names_scroll[0] + "_bg2_scr1", "offset": 0xCADCCC, "type": "byte", "field": "check"},                   # SCR1.
	{"name": m_field_names_scroll[0] + "_bg2_scr2", "offset": 0xCADCCD, "type": "byte", "field": "check"},                   # SCR2.
	{"name": m_field_names_scroll[0] + "_bg2_scr3", "offset": 0xCADCCE, "type": "byte", "field": "check"},                   # SCR3.
	{"name": m_field_names_scroll[0] + "_bg2_scr4", "offset": 0xCADCCF, "type": "byte", "field": "check"},                   # SCR4.
	
	# BG2, distortion checks.
	
	{"name": m_field_names_distortion[0] + "_bg2_dst1", "offset": 0xCADCD0, "type": "byte", "field": "check"},               # DST1.
	{"name": m_field_names_distortion[0] + "_bg2_dst2", "offset": 0xCADCD1, "type": "byte", "field": "check"},               # DST2.
	{"name": m_field_names_distortion[0] + "_bg2_dst3", "offset": 0xCADCD2, "type": "byte", "field": "check"},               # DST3.
	{"name": m_field_names_distortion[0] + "_bg2_dst4", "offset": 0xCADCD3, "type": "byte", "field": "check"}                # DST4.
)

insertions_scroll = (
	
	# Scroll entry 1.
	
	{"name": m_field_names_scroll[1], "offset": 0xCAF262, "type": "short", "field": "entry"},                                # Duration.
	{"name": m_field_names_scroll[3], "offset": 0xCAF264, "type": "short", "field": "entry"},                                # Hor. mov.
	{"name": m_field_names_scroll[5], "offset": 0xCAF266, "type": "short", "field": "entry"},                                # Ver. mov.
	{"name": m_field_names_scroll[2], "offset": 0xCAF268, "type": "short", "field": "entry"},                                # Hor. acc.
	{"name": m_field_names_scroll[4], "offset": 0xCAF26A, "type": "short", "field": "entry"}                                 # Ver. acc.
)

insertions_distortion = (
	
	# Distortion entry.
	
	{"name": m_field_names_distortion[10], "offset": 0xCAF719, "type": "short", "field": "entry"},                           # Duration.
	{"name": m_field_names_distortion[1], "offset": 0xCAF71B, "type": "byte", "field": "combobox_idx"},                      # Type.
	{"name": m_field_names_distortion[4], "offset": 0xCAF71C, "type": "short", "field": "entry"},                            # Ripple frequency.
	{"name": m_field_names_distortion[2], "offset": 0xCAF71E, "type": "short", "field": "entry"},                            # Ripple amplitude.
	{"name": m_field_names_distortion[6], "offset": 0xCAF720, "type": "byte", "field": "entry"},                             # Acceleration.
	{"name": m_field_names_distortion[8], "offset": 0xCAF721, "type": "short", "field": "entry"},                            # Compression rate.
	{"name": m_field_names_distortion[5], "offset": 0xCAF723, "type": "short", "field": "entry"},                            # Ripple frequency acc.
	{"name": m_field_names_distortion[3], "offset": 0xCAF725, "type": "short", "field": "entry"},                            # Ripple amplitude acc.
	{"name": m_field_names_distortion[7], "offset": 0xCAF727, "type": "byte", "field": "entry"},                             # Speed.
	{"name": m_field_names_distortion[9], "offset": 0xCAF728, "type": "short", "field": "entry"}                             # Compression rate acc.
)