# --------------------------------------------------------------------------------------------------------------------------



# EarthBound Battle Background Previewer

# https://github.com/Vittorioux/EBBG-Previewer

# Constants file.



# -------------------------------------------------------- Imports ---------------------------------------------------------



import os



# ------------------------------------------------------- Constants --------------------------------------------------------



# Folder and file where some of the application data will be stored.

DATA_FOLDER_NAME = "ebbg-previewer_data"
DATA_FILE_NAME = os.path.join(DATA_FOLDER_NAME, "data.conf")

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# SuperFamiconV will produce some temporary files.

# BG1.
TEMP_PALETTE_OUT_GRAY_1 = os.path.join(DATA_FOLDER_NAME, "temp_palette_out_gray_1.bin")
TEMP_PALETTE_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_palette_out_1.bin")
TEMP_TILES_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_tiles_out_1.bin")
TEMP_TILEMAP_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_tilemap_out_1.bin")

#BG2.
TEMP_PALETTE_OUT_GRAY_2 = os.path.join(DATA_FOLDER_NAME, "temp_palette_out_gray_2.bin")
TEMP_PALETTE_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_palette_out_2.bin")
TEMP_TILES_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_tiles_out_2.bin")
TEMP_TILEMAP_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_tilemap_out_2.bin")

# Temp images with corrected formats.
TEMP_IMG_OUT_1 = os.path.join(DATA_FOLDER_NAME, "temp_img_out_1.png")
TEMP_IMG_OUT_2 = os.path.join(DATA_FOLDER_NAME, "temp_img_out_2.png")

TEMP_IMG_OUT_GRAY_1 = os.path.join(DATA_FOLDER_NAME, "temp_img_out_gray_1.png")
TEMP_IMG_OUT_GRAY_2 = os.path.join(DATA_FOLDER_NAME, "temp_img_out_gray_2.png")

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Program version.

VERSION = "1.031"

# 'About' text.

ABOUT_TEXT = f"""EarthBound BG Previewer v{VERSION}

Use this simple program to quickly preview palette cycling, scrolling and distortion settings on EarthBound battle backgrounds.

This program and its source code operate under an MIT License:
https://github.com/Vittorioux/EBBG-Previewer

This program uses Inhal by devinacker and SuperFamiconV by Optiroc.

Inhal/Exhal:
https://github.com/devinacker/exhal

SuperFamiconV:
https://github.com/Optiroc/SuperFamiconv"""

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Field names in the top frame.

t_field_names = ["setting_emulator", "setting_rom", "setting_bg1", "setting_bg2", "setting_enemy_group", "setting_project"]

m_field_names_palette = ["setting_bpp", "setting_cyc_type", "setting_cyc_1_begin", "setting_cyc_1_end", "setting_cyc_2_begin", "setting_cyc_2_end", "setting_cyc_speed"]

m_field_names_scroll = ["setting_scr_check", "setting_scr_dur", "setting_scr_hacc", "setting_scr_hmov", "setting_scr_vacc", "setting_scr_vmov"]

m_field_names_distortion = ["setting_dst_check", "setting_dst_type", "setting_dst_rip_amp", "setting_dst_rip_amp_acc", "setting_dst_rip_freq", "setting_dst_rip_freq_acc", "setting_dst_acc", "setting_dst_spd", "setting_dst_cr", "setting_dst_cr_acc", "setting_dst_dur"]

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Default data file contents (the first four names are hardcoded).

DEFAULT_DATA = f"""# DO NOT EDIT THIS FILE

# PROGRAM GEOMETRY

width: 800
height: 575
x_pos: 100
y_pos: 100

# TOP FRAME FIELDS

{t_field_names[0]}: 
{t_field_names[1]}: 
{t_field_names[2]}: 
{t_field_names[3]}:

# MIDDLE FRAME FIELDS 
"""

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# CoilSnake YML key lists.

yml_bg_data = ["Colour depth", "Distortion 1", "Distortion 2", "Distortion 3", "Distortion 4", "Palette Cycle", "Palette Cycle 1 Begin", "Palette Cycle 1 End", "Palette Cycle 2 Begin", "Palette Cycle 2 End", "Palette-changing speed", "Scrolling Movement 1", "Scrolling Movement 2", "Scrolling Movement 3", "Scrolling Movement 4"]

yml_bg_scrolling = ["Duration", "Horizontal Acceleration", "Horizontal Movement", "Vertical Acceleration", "Vertical Movement"]

yml_bg_distortion = ["Ripple Amplitude", "Ripple Amplitude Acceleration", "Ripple Frequency", "Ripple Frequency Acceleration", "Speed", "Type", "Unknown A", "Unknown B", "Unknown C", "Unknown D"]

# CoilSnake YML value lists.

yml_cycle_type_names = ["none", "'1'", "1 + 2", "1 (reverse)"]

yml_distortion_type_names = ["unknown type 0", "horizontal, smooth", "horizontal, interlaced", "vertical, smooth", "unknown type 4"]

# Structure types.

BG_DATA = "bg_data"
BG_SCROLLING = "bg_scrolling"
BG_DISTORTION = "bg_distortion"

# Valid project files.

valid_project_files = ["Project.snake", "bg_data_table.yml", "bg_scrolling_table.yml", "bg_distortion_table.yml"]

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Other constants.

BANK_C0_OFFSET = 0xC00000

CYCLE_TYPE_NAMES = ["None", "Cycle 1", "Cycle 1+2", "Cycle 1 (reverse)"]
DST_TYPE_NAMES = ["None (Unk type 0)", "Horizontal, smooth", "Horizontal, interlaced", "Vertical, smooth", "Hor, interl 2 (Unk type 4)"]

# We need to overwrite some safe locations in ROM, making sure that
# CoilSnake doesn't touch them. Text can be sacrificed forthis, since
# it's irrelevant for this tool anyway.

GFX_25_OFFSET = 0xC50000
ARR_25_OFFSET = 0xC58000
PAL_25_OFFSET = 0xC5F000

GFX_50_OFFSET = 0xC60000
ARR_50_OFFSET = 0xC68000
PAL_50_OFFSET = 0xC6F000

SCR_ENTRY_SIZE = 10
DST_ENTRY_SIZE = 17

MENU_BG1_OFFSET = 0xC0B5F1
MENU_BG2_OFFSET = 0xC0B5EC

MAX_ENEMY_GROUP = 483

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Tuple of dicts with forced ROM insertions at static addresses.

forced_rom_insertions = (
	
	# ASM Code to make it so the game goes directly to show the BGs.
	# TODO: document the actual instructions in commentaries.
	
	{"offset": 0xC0B7EB, "bytes": [0x80, 0x02]},                           # Skip intro logos, gas station screen, title.
	
	# Constantly animate the background, plus detect Y button for pause and L button to switch letterbox size.
	{"offset": 0xC1ED6A, "bytes": [0x22, 0xD2, 0xDA, 0xC4, 0xA9, 0x02, 0x00, 0x22, 0xE8, 0x29, 0xC4, 0x22, 0x3F, 0xDB, 0xC2, 0x22, 0x26, 0x8B, 0xC0, 0x22, 0xF3, 0xDA, 0xC4, 0x22, 0x56, 0x87, 0xC0, 0xAD, 0x65, 0x00, 0x29, 0x00, 0x40, 0xD0, 0xF4, 0xAD, 0x6D, 0x00, 0x29, 0x00, 0x10, 0xF0, 0x04, 0x5C, 0x34, 0xDB, 0xC4, 0x80, 0xDA]},
	
	# Custom routines from $C4DAD2 to $C4DCF5 at most (we have 547 free bytes).
	
	# Clear the first window tile in VRAM.
	{"offset": 0xC4DAD2, "bytes": [0xC2, 0x31, 0x0B, 0x7B, 0x69, 0xEA, 0xFF, 0x5B, 0xA9, 0x80, 0x32, 0x85, 0x0E, 0xA9, 0x7E, 0x00, 0x85, 0x10, 0xA9, 0x00, 0x00, 0xA2, 0x10, 0x00, 0xA0, 0x00, 0x60, 0x22, 0x16, 0x86, 0xC0, 0x2B, 0x6B]},
	
	# Implement letterbox switching routine.
	{"offset": 0xC4DAF3, "bytes": [0xAD, 0x6D, 0x00, 0x29, 0x20, 0x00, 0xF0, 0x38, 0xAD, 0xB2, 0xAD, 0xF0, 0x18, 0xC9, 0x42, 0x00, 0xF0, 0x21, 0x18, 0x69, 0x0A, 0x00, 0x8D, 0xB2, 0xAD, 0xAD, 0xB4, 0xAD, 0x38, 0xE9, 0x0A, 0x00, 0x8D, 0xB4, 0xAD, 0x80, 0x17, 0xA9, 0x2E, 0x00, 0x8D, 0xB2, 0xAD, 0xA9, 0xB1, 0x00, 0x8D, 0xB4, 0xAD, 0x80, 0x09, 0x9C, 0xB2, 0xAD, 0xA9, 0xE0, 0x00, 0x8D, 0xB4, 0xAD, 0x22, 0xAC, 0xD0, 0xC2, 0x6B]},
	
	# Implement battle tester.
	{"offset": 0xC4DB34, "bytes": [0xA9, 0x01, 0x00, 0x8D, 0xCD, 0x99, 0x22, 0xD9, 0x00, 0xC2, 0x22, 0x3F, 0x7C, 0xC4, 0xA9, 0x01, 0x00, 0x22, 0x63, 0x49, 0xC4, 0x22, 0x87, 0x7F, 0xC4, 0xA9, 0x01, 0x00, 0x22, 0x38, 0x2F, 0xC2]},
	
	# Battle stuff initialization.
	{"offset": 0xC4DB54, "bytes": [0xC2, 0x31, 0x0B, 0x7B, 0x69, 0xEA, 0xFF, 0x5B, 0xA9, 0x1E, 0x00, 0x8D, 0x13, 0x9A, 0x8D, 0x72, 0x9A, 0x8D, 0xD1, 0x9A, 0xA9, 0x71, 0x00, 0x8D, 0xCE, 0x99, 0x8D, 0x30, 0xB6, 0x8D, 0x80, 0xB6, 0xA9, 0x72, 0x00, 0x8D, 0x2D, 0x9A, 0x8D, 0x37, 0xB6, 0x8D, 0x87, 0xB6, 0xA9, 0x73, 0x00, 0x8D, 0x8C, 0x9A, 0x8D, 0x3E, 0xB6, 0x8D, 0x8E, 0xB6, 0x22, 0x3F, 0x7C, 0xC4, 0xA9, 0x01, 0x00, 0x22, 0x63, 0x49, 0xC4, 0xA9, 0x03, 0x00, 0x8D, 0xA4, 0x98, 0xA9, 0x01, 0x00, 0x8D, 0x6F, 0x98, 0x1A, 0x8D, 0x70, 0x98, 0x1A, 0x8D, 0x71, 0x98, 0x22, 0x3B, 0xDD, 0xC1, 0x22, 0xD5, 0x2D, 0xC1, 0x22, 0xD4, 0xE4, 0xC3, 0xA9, 0xC7, 0xDB, 0x85, 0x0E, 0xA9, 0xC4, 0x00, 0x85, 0x10, 0x22, 0x1C, 0xDC, 0xC1, 0x2B, 0x6B]},
	
	# Text ("@This is a test battle generated to preview the background.").
	{"offset": 0xC4DBC7, "bytes": [0x18, 0x01, 0x0E, 0x70, 0x84, 0x98, 0x99, 0xA3, 0x50, 0x99, 0xA3, 0x50, 0x91, 0x50, 0xA4, 0x95, 0xA3, 0xA4, 0x50, 0x92, 0x91, 0xA4, 0xA4, 0x9C, 0x95, 0x50, 0x97, 0x95, 0x9E, 0x95, 0xA2, 0x91, 0xA4, 0x95, 0x94, 0x50, 0xA4, 0x9F, 0x50, 0xA0, 0xA2, 0x95, 0xA6, 0x99, 0x95, 0xA7, 0x50, 0xA4, 0x98, 0x95, 0x50, 0x92, 0x91, 0x93, 0x9B, 0x97, 0xA2, 0x9F, 0xA5, 0x9E, 0x94, 0x5E, 0x10, 0x01, 0x02]},
	
	# Battle hijacks.
	
	# Avoid showing swirl when loading the battle.
	{"offset": 0xC22FA9, "bytes": [0x4C, 0xC0, 0x2F]},
	
	# Always load BG1 and BG2 in battle (and no letterbox).
	{"offset": 0xC248BD, "bytes": [0xA9, 0x02, 0x00, 0x85, 0x2B, 0xA9, 0x01, 0x00, 0x85, 0x2D, 0x3A, 0x85, 0x29, 0x4C, 0xE0, 0x48]},
	
	# New controls in battle (letterbox + pause).
	{"offset": 0xC24A71, "bytes": [0x22, 0x54, 0xDB, 0xC4, 0x22, 0x56, 0x87, 0xC0, 0xAD, 0x65, 0x00, 0x29, 0x00, 0x40, 0xD0, 0xF4, 0x22, 0x3F, 0xDB, 0xC2, 0x22, 0xF3, 0xDA, 0xC4, 0xA9, 0x02, 0x00, 0x22, 0xE8, 0x29, 0xC4, 0x4C, 0x75, 0x4A]},
	
	{"offset": MENU_BG1_OFFSET, "bytes": [0x01]},                          # Load background 1 as layer 1.
	{"offset": MENU_BG2_OFFSET, "bytes": [0x02]},                          # Load background 2 as layer 2.
	
	{"offset": 0xC2FFFF, "bytes": [0xEA]},                                 # "ROM was modified by this program" mark.
	
	# BG1.
	
	{"offset": 0xCADCB2, "bytes": [0x19]},                                 # Graphics.
	{"offset": 0xCADCB3, "bytes": [0x19]},                                 # Palette.
	
	{"offset": 0xCADCBB, "bytes": [0x01]},                                 # SCR1.
	{"offset": 0xCADCBC, "bytes": [0x02]},                                 # SCR2.
	{"offset": 0xCADCBD, "bytes": [0x03]},                                 # SCR3.
	{"offset": 0xCADCBE, "bytes": [0x04]},                                 # SCR4.
	
	{"offset": 0xCADCBF, "bytes": [0x01]},                                 # DST1.
	{"offset": 0xCADCC0, "bytes": [0x02]},                                 # DST2.
	{"offset": 0xCADCC1, "bytes": [0x03]},                                 # DST3.
	{"offset": 0xCADCC2, "bytes": [0x04]},                                 # DST4.
	
	# BG2.
	
	{"offset": 0xCADCC3, "bytes": [0x32]},                                 # Graphics.
	{"offset": 0xCADCC4, "bytes": [0x32]},                                 # Palette.
	
	{"offset": 0xCADCCC, "bytes": [0x05]},                                 # SCR1.
	{"offset": 0xCADCCD, "bytes": [0x06]},                                 # SCR2.
	{"offset": 0xCADCCE, "bytes": [0x07]},                                 # SCR3.
	{"offset": 0xCADCCF, "bytes": [0x08]},                                 # SCR4.
	
	{"offset": 0xCADCD0, "bytes": [0x05]},                                 # DST1.
	{"offset": 0xCADCD1, "bytes": [0x06]},                                 # DST2.
	{"offset": 0xCADCD2, "bytes": [0x07]},                                 # DST3.
	{"offset": 0xCADCD3, "bytes": [0x08]}                                  # DST4.
)

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Tuple of dicts with ROM instertions at dynamic addresses, which we get from pointers.

# Valid pointer types are 'xl' and 'dp'.

dynamic_rom_insertions = (
	
	# Graphics, arrangements and palette for BG1 (entries 25).
	
	{"pointer_address": 0xC2D1BA, "pointer_type": "dp", "insertion_offset": 100, "bytes": [0x00, 0x00, 0xC5, 0x00]},
	{"pointer_address": 0xC2D2C1, "pointer_type": "dp", "insertion_offset": 100, "bytes": [0x00, 0x80, 0xC5, 0x00]},
	{"pointer_address": 0xC2D3BB, "pointer_type": "dp", "insertion_offset": 100, "bytes": [0x00, 0xF0, 0xC5, 0x00]},
	
	# Graphics, arrangements and palette for BG2 (entries 50).
	
	{"pointer_address": 0xC2D1BA, "pointer_type": "dp", "insertion_offset": 200, "bytes": [0x00, 0x00, 0xC6, 0x00]},
	{"pointer_address": 0xC2D2C1, "pointer_type": "dp", "insertion_offset": 200, "bytes": [0x00, 0x80, 0xC6, 0x00]},
	{"pointer_address": 0xC2D3BB, "pointer_type": "dp", "insertion_offset": 200, "bytes": [0x00, 0xF0, 0xC6, 0x00]}
)

# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# Tuples of dicts for ROM insertions, containing each relevant field, its ROM offset, field type, and data type.

# Valid field types are 'combobox_val', 'combobox_idx', 'check' and 'entry'.

# Valid data types are 'byte' and 'short'.

# (Full customization isn't properly programmed in 'logic.py' as of now).

insertions_palette = (
	
	# BG1, palette settings.

	{"name": m_field_names_palette[0] + "_bg1", "offset": 0xCADCB4, "type": "byte", "field": "combobox_val"},                # BPP.
	{"name": m_field_names_palette[1] + "_bg1", "offset": 0xCADCB5, "type": "byte", "field": "combobox_idx"},                # Type.
	{"name": m_field_names_palette[2] + "_bg1", "offset": 0xCADCB6, "type": "byte", "field": "entry"},                       # Cycle 1 begin.
	{"name": m_field_names_palette[3] + "_bg1", "offset": 0xCADCB7, "type": "byte", "field": "entry"},                       # Cycle 1 end.
	{"name": m_field_names_palette[4] + "_bg1", "offset": 0xCADCB8, "type": "byte", "field": "entry"},                       # Cycle 2 begin.
	{"name": m_field_names_palette[5] + "_bg1", "offset": 0xCADCB9, "type": "byte", "field": "entry"},                       # Cycle 2 end.
	{"name": m_field_names_palette[6] + "_bg1", "offset": 0xCADCBA, "type": "byte", "field": "entry"},                       # Speed.
	
	# BG2, palette settings.
	
	{"name": m_field_names_palette[0] + "_bg2", "offset": 0xCADCC5, "type": "byte", "field": "combobox_val"},                # BPP.
	{"name": m_field_names_palette[1] + "_bg2", "offset": 0xCADCC6, "type": "byte", "field": "combobox_idx"},                # Type.
	{"name": m_field_names_palette[2] + "_bg2", "offset": 0xCADCC7, "type": "byte", "field": "entry"},                       # Cycle 1 begin.
	{"name": m_field_names_palette[3] + "_bg2", "offset": 0xCADCC8, "type": "byte", "field": "entry"},                       # Cycle 1 end.
	{"name": m_field_names_palette[4] + "_bg2", "offset": 0xCADCC9, "type": "byte", "field": "entry"},                       # Cycle 2 begin.
	{"name": m_field_names_palette[5] + "_bg2", "offset": 0xCADCCA, "type": "byte", "field": "entry"},                       # Cycle 2 end.
	{"name": m_field_names_palette[6] + "_bg2", "offset": 0xCADCCB, "type": "byte", "field": "entry"}                        # Speed.
)

insertions_check = (
	
	# BG1, scroll checks.
	
	{"name": m_field_names_scroll[0] + "_bg1_scr1", "offset": 0xCADCBB, "type": "byte", "field": "check"},                   # SCR1.
	{"name": m_field_names_scroll[0] + "_bg1_scr2", "offset": 0xCADCBC, "type": "byte", "field": "check"},                   # SCR2.
	{"name": m_field_names_scroll[0] + "_bg1_scr3", "offset": 0xCADCBD, "type": "byte", "field": "check"},                   # SCR3.
	{"name": m_field_names_scroll[0] + "_bg1_scr4", "offset": 0xCADCBE, "type": "byte", "field": "check"},                   # SCR4.
	
	# BG1, distortion checks.
	
	{"name": m_field_names_distortion[0] + "_bg1_dst1", "offset": 0xCADCBF, "type": "byte", "field": "check"},               # DST1.
	{"name": m_field_names_distortion[0] + "_bg1_dst2", "offset": 0xCADCC0, "type": "byte", "field": "check"},               # DST2.
	{"name": m_field_names_distortion[0] + "_bg1_dst3", "offset": 0xCADCC1, "type": "byte", "field": "check"},               # DST3.
	{"name": m_field_names_distortion[0] + "_bg1_dst4", "offset": 0xCADCC2, "type": "byte", "field": "check"},               # DST4.
	
	# BG2, scroll checks.
	
	{"name": m_field_names_scroll[0] + "_bg2_scr1", "offset": 0xCADCCC, "type": "byte", "field": "check"},                   # SCR1.
	{"name": m_field_names_scroll[0] + "_bg2_scr2", "offset": 0xCADCCD, "type": "byte", "field": "check"},                   # SCR2.
	{"name": m_field_names_scroll[0] + "_bg2_scr3", "offset": 0xCADCCE, "type": "byte", "field": "check"},                   # SCR3.
	{"name": m_field_names_scroll[0] + "_bg2_scr4", "offset": 0xCADCCF, "type": "byte", "field": "check"},                   # SCR4.
	
	# BG2, distortion checks.
	
	{"name": m_field_names_distortion[0] + "_bg2_dst1", "offset": 0xCADCD0, "type": "byte", "field": "check"},               # DST1.
	{"name": m_field_names_distortion[0] + "_bg2_dst2", "offset": 0xCADCD1, "type": "byte", "field": "check"},               # DST2.
	{"name": m_field_names_distortion[0] + "_bg2_dst3", "offset": 0xCADCD2, "type": "byte", "field": "check"},               # DST3.
	{"name": m_field_names_distortion[0] + "_bg2_dst4", "offset": 0xCADCD3, "type": "byte", "field": "check"}                # DST4.
)

insertions_scroll = (
	
	# Scroll entry 1.
	
	{"name": m_field_names_scroll[1], "offset": 0xCAF262, "type": "short", "field": "entry"},                                # Duration.
	{"name": m_field_names_scroll[3], "offset": 0xCAF264, "type": "short", "field": "entry"},                                # Hor. mov.
	{"name": m_field_names_scroll[5], "offset": 0xCAF266, "type": "short", "field": "entry"},                                # Ver. mov.
	{"name": m_field_names_scroll[2], "offset": 0xCAF268, "type": "short", "field": "entry"},                                # Hor. acc.
	{"name": m_field_names_scroll[4], "offset": 0xCAF26A, "type": "short", "field": "entry"}                                 # Ver. acc.
)

insertions_distortion = (
	
	# Distortion entry.
	
	{"name": m_field_names_distortion[10], "offset": 0xCAF719, "type": "short", "field": "entry"},                           # Duration.
	{"name": m_field_names_distortion[1], "offset": 0xCAF71B, "type": "byte", "field": "combobox_idx"},                      # Type.
	{"name": m_field_names_distortion[4], "offset": 0xCAF71C, "type": "short", "field": "entry"},                            # Ripple frequency.
	{"name": m_field_names_distortion[2], "offset": 0xCAF71E, "type": "short", "field": "entry"},                            # Ripple amplitude.
	{"name": m_field_names_distortion[6], "offset": 0xCAF720, "type": "byte", "field": "entry"},                             # Acceleration.
	{"name": m_field_names_distortion[8], "offset": 0xCAF721, "type": "short", "field": "entry"},                            # Compression rate.
	{"name": m_field_names_distortion[5], "offset": 0xCAF723, "type": "short", "field": "entry"},                            # Ripple frequency acc.
	{"name": m_field_names_distortion[3], "offset": 0xCAF725, "type": "short", "field": "entry"},                            # Ripple amplitude acc.
	{"name": m_field_names_distortion[7], "offset": 0xCAF727, "type": "byte", "field": "entry"},                             # Speed.
	{"name": m_field_names_distortion[9], "offset": 0xCAF728, "type": "short", "field": "entry"}                             # Compression rate acc.
)
